kind: pipeline
type: docker
name: run_apps

steps:
  - name: Run Backend
    commands:
      - cd Watch2Gether_Backend
      - docker-compose up -d

  - name: Run Frontend
    commands:
      - cd watch2gether_client
      - docker-compose up -d
