kind: pipeline
name: default

steps:
- name: test
  image: docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - cd Watch2Gether_Backend
  - docker-compose up -d
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock