version: '3.7'
services:
  web:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      REACT_APP_WATCH_2_GETHER_BACKEND_ADDRESS: "http://localhost:5000/"
