version: '3.7'
services:
  web:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:80"
    environment:
      - REACT_APP_WATCH_2_GETHER_BACKEND_ADDRESS=https://localhost:7165/
