version: "3.7"
services:
  react:
    build: .
    restart: always
    ports:
      - "4173:4173"
    environment:
      - VITE_WATCH_2_GETHER_BACKEND_ADDRESS=https://watchwithfriends-backend.mt-dev.site
